version: '3.8'

services:
  php-site:
    build: .
    container_name: nutrithub_php
    ports:
      - "8080:80"
    volumes:
      - ./site-php/public:/var/www/html
      - ./site-php/data:/var/www/data
    restart: always

  html-site:
    image: nginx:alpine
    container_name: nutrithub_html
    ports:
      - "8081:80"
    volumes:
      - ./site-html:/usr/share/nginx/html:ro
    restart: always